name: FLUREST
description: Aplicacion hehca en Flutter, para restaurantes..

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  flutter_swiper: ^1.1.4
  polygon_clipper: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
   
   - assets/lomo.jpg
   - assets/ceviche.jpg
   - assets/arroz.jpg
   - assets/cerberodev.png

  fonts:
    - family: Timesroman
      fonts:
        - asset: assets/serif-regular.ttf
        - asset: assets/serifbold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf
