name: FLUREST
description: Aplicacion hehca en Flutter, para restaurantes..

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  flutter_swiper: ^1.1.4
  polygon_clipper: ^1.0.1
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  
  assets:
   
   - assets/
   - assets/logo.png
   - assets/lomo.jpg
   - assets/ceviche.jpg
   - assets/arroz.jpg
   - assets/cerberodev.png
   

  fonts:
    - family: Timesroman
      fonts:
        - asset: assets/serif-regular.ttf
        - asset: assets/serifbold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf
